version: "3"

services:
  product:
    build:
      context: ./product
    ports:
      - 8081:8081
    environment:
      - SERVICE_PORT=:8081
  catalog:
    build:
      context: ./catalog
    ports:
      - 8082:8082
    environment:
      - SERVICE_PORT=:8082
      - PRODUCTS_URL=http://product:8081
  checkout:
    build:
      context: ./checkout
    ports:
      - 8083:8083
    environment:
      - SERVICE_PORT=:8083
      - PRODUCTS_URL=http://product:8081