version: "3"

services:

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG-COOKIE: ABC123
      RABBITMQ_DEFAULT_USER: rabbitmq-user
      RABBITMQ_DEFAULT_PASS: rabbitmq-pass
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  product:
    build:
      context: ./product
    ports:
      - 8081:8081
    environment:
      SERVICE_PORT: :8081

  catalog:
    build:
      context: ./catalog
    ports:
      - 8082:8082
    environment:
      SERVICE_PORT: :8082
      PRODUCTS_URL: http://product:8081

  checkout:
    build:
      context: ./checkout
    ports:
      - 8083:8083
    environment:
      SERVICE_PORT: :8083
      PRODUCTS_URL: http://product:8081
      RABBITMQ_DEFAULT_USER: rabbitmq-user
      RABBITMQ_DEFAULT_PASS: rabbitmq-pass
      RABBITMQ_DEFAULT_HOST: rabbitmq
      RABBITMQ_DEFAULT_PORT: 5672
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_CONSUMER_EXCHANGE: checkout_exchange

  order:
    build:
      context: ./order
    environment:
      PRODUCTS_URL: http://product:8081
      RABBITMQ_DEFAULT_USER: rabbitmq-user
      RABBITMQ_DEFAULT_PASS: rabbitmq-pass
      RABBITMQ_DEFAULT_HOST: rabbitmq
      RABBITMQ_DEFAULT_PORT: 5672
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_CONSUMER_QUEUE: checkout_queue
      REDIS_HOST: redis:6379