apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-payment
spec:
  selector:
    matchLabels:
      app: order-payment

  template:
    metadata:
      labels:
        app: order-payment
    spec:
      containers:
        - name: order-payment
          image: h3170n/microservices-in-go-order
          ports:
            - containerPort: 6572
          env:
            - name: ORDER_QUEUE
              value: "payment"
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbitmq-user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbitmq-pass"
            - name: RABBITMQ_DEFAULT_HOST
              value: "rabbitmq-service"
            - name: RABBITMQ_DEFAULT_PORT
              value: "5672"
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"
            - name: RABBITMQ_PAYMENT_QUEUE
              value: "payment_queue"
            - name: REDIS_HOST
              value: "redis-service:6379"

---

apiVersion: v1
kind: Service
metadata:
  name: order-payment-service
  labels:
    app: order-payment-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6572
  selector:
    app: order-payment