apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  selector:
    matchLabels:
      app: payment

  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: h3170n/microservices-in-go-payment
          ports:
            - containerPort: 6572
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbitmq-user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbitmq-pass"
            - name: RABBITMQ_DEFAULT_HOST
              value: "rabbitmq-service"
            - name: RABBITMQ_DEFAULT_PORT
              value: "5672"
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"
            - name: RABBITMQ_ORDER_QUEUE
              value: "order_queue"
            - name: RABBITMQ_PAYMENT_EXCHANGE
              value: "payment_exchange"

---

apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6572
  selector:
    app: payment